blank_issues_enabled: true
contact_links:
  - name: Give feedback about App Permissions
    url: https://t.maze.co/266411709?guerilla=true&source=github
    about: Share your overall experience and help us improve the feature by filling our survey