name: Flutter CI

on:
  push:
    branches:
      - security-center
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v2
      - run: melos generate
      - run: melos gen-l10n
      - uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}-generated

  analyze:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Restore repository cache
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}-generated
          restore-keys: |
            ${{ runner.os }}-repo-
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v2
      - run: melos analyze --fatal-infos

  format:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Restore repository cache
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}-generated
          restore-keys: |
            ${{ runner.os }}-repo-
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v2
      - run: melos format:exclude

  test:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Restore repository cache
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}-generated
          restore-keys: |
            ${{ runner.os }}-repo-
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v2
      - run: sudo apt update && sudo apt install -y lcov
      - run: melos coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  security-center:
    runs-on: ubuntu-22.04
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Restore repository cache
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}-generated
          restore-keys: |
            ${{ runner.os }}-repo-
      - uses: Atsumi3/actions-setup-fvm@0.0.3
      - uses: bluefireteam/melos-action@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y clang cmake libglib2.0-dev libgtk-3-dev liblzma-dev ninja-build pkg-config polkitd xvfb
      - name: Setup apparmor prompting
        run: |
          sudo snap refresh snapd --channel=latest/edge
          sudo snap install prompting-client
          sudo snap set system experimental.apparmor-prompting=true
      - name: Setup polkit rules
        run: sudo cp packages/security_center/integration_test/assets/snapd-ci.pkla /var/lib/polkit-1/localauthority/50-local.d/
      - name: Run integration tests
        working-directory: packages/security_center
        run: xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' flutter test integration_test
